language: php

php:
  - 5.3
  - 5.4
#  - 5.5
#  - 5.6
  - hhvm
  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server
  - memcached

before_script:
  # get the yii framework files
  - git clone https://github.com/yiisoft/yii.git ../yii
  # create the test database
  - chmod +x ./protected/tests/travis/*.sh
  - ./protected/tests/travis/mysql-setup.sh
  # initiate the test database to the latest version
  - chmod +x ./protected/yiic
  - ./protected/yiic migrate
  # change the active directory to the tests
  - cd protected/tests
  # make sure that the phpunit and phpunit_selenium are the latest version
#  - pear install phpunit/phpunit_selenium
#  - pear upgrade -f phpunit/phpunit_selenium

script:
  phpunit unit
  # phpunit --colors --verbose functional
