language: php

php:
  - 5.3
  - 5.4
#  - 5.5
#  - 5.6
  - hhvm
  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server
  - memcached

before_script:
  # Install php unit selenium extension.
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/PHPUnit_Selenium
  - phpenv rehash

  # Start selenium server.
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - nohup java -jar selenium-server-standalone-2.41.0.jar -browserSessionReuse -debug > selenium-output &
  - sleep 3 # Give selenium server time to start.

  # get the yii framework files
  - git clone https://github.com/yiisoft/yii.git ../yii
  # create the test database
  - chmod +x ./protected/tests/travis/*.sh
  - ./protected/tests/travis/mysql-setup.sh
  # initiate the test database to the latest version
  - chmod +x ./protected/yiic
  - ./protected/yiic migrate
  # change the active directory to the tests
  - cd protected/tests

script:
  phpunit unit
  # phpunit --colors --verbose functional
